language: node_js

git:
  depth: 1

branches:
  only:
    - master

node_js:
  - '8'

before_install:
  - openssl aes-256-cbc -K $encrypted_db7315ec298a_key -iv $encrypted_db7315ec298a_iv -in passwd.js.enc -out passwd.js -d

install:
  - npm install

script: node index.js


